### ISSUE TITLE
啊，还有这个demo好像有一个bug

### ISSUE THREAD

**Issue by SaltedFish-Extreme** [goweii/SwipeBack#10]
如图，如果开了不止一个新页面，全局滑动返回上一个activity时，如果带有收缩效果的话，有时候会让上一个的收缩效果重叠，不知道会不会内存泄漏啥的

**Comment by SaltedFish-Extreme** [comment]
![微信图片_20211217173822](https://user-images.githubusercontent.com/54784104/146524636-355ca137-bdfd-4002-9e89-9385d975b3c1.jpg)
![微信图片_20211217173818](https://user-images.githubusercontent.com/54784104/146524641-c54dc5af-654c-4a82-a637-1220252ec28a.jpg)

**Comment by goweii** [comment]
不会内存泄露，只是个显示bug。后面有空修复。

**Comment by SaltedFish-Extreme** [comment]
> 不会内存泄露，只是个显示bug。后面有空修复。

啊，好的，麻烦了

**Comment by goweii** [comment]
已修复，升级2.0.3

**Comment by SaltedFish-Extreme** [comment]
> 已修复，升级2.0.3

好的😉
