### ISSUE TITLE
老哥，这个有个bug，我在activity基类里设置了全局侧滑返回，在MainActivity的onCreate里取消了，但是打开新的activity滑动返回到MainActivity，又可以侧滑返回到桌面了😂

### ISSUE THREAD

**Issue by SaltedFish-Extreme** [goweii/SwipeBack#11]
不知道是不是这么写，老哥能帮忙看看吗

![image](https://user-images.githubusercontent.com/54784104/152757102-56185974-0cfc-447f-a136-3e121026b2e2.png)

![image](https://user-images.githubusercontent.com/54784104/152757132-dbecb27b-5974-4098-b3b3-a016c5165974.png)

**Comment by goweii** [comment]
第二个activity打开时，重新置成true了，覆盖了mainactivity的false

**Comment by SaltedFish-Extreme** [comment]
> 第二个activity打开时，重新置成true了，覆盖了mainactivity的false

这样啊😂，我改成在onResume里面取消全局侧滑好了👌
