### ISSUE TITLE
话说老哥，还有个问题，当前页面如果有夜间模式的开关，切换之后，当前页的全局侧滑就失效了，我在你的玩安卓app试了也是这个情况😂

### ISSUE THREAD

**Issue by SaltedFish-Extreme** [goweii/SwipeBack#12]
还有，我好像发现在基类里配置了全局侧滑之后，在子类的onCreate或者onResume里面取消全局侧滑都没有用，但是只有MainActivity子类有用🤔

**Comment by goweii** [comment]
重建这个导致无法侧滑这个问题我周末看下。
全局配置放到application去设置

**Comment by SaltedFish-Extreme** [comment]
> 重建这个导致无法侧滑这个问题我周末看下。 全局配置放到application去设置

老哥，我在application里面全局配置
````kotlin
SwipeBack.getInstance().run {
     init(this@MyApplication)
     //全局可滑动返回
     isRootSwipeBackEnable = true
     //强制边缘侧滑返回(横向列表适配器)
     isSwipeBackForceEdge = true
     //右滑方向
     swipeBackDirection = SwipeBackDirection.RIGHT
     //底部activity联动视差效果
     swipeBackTransformer = ParallaxSwipeBackTransformer()
  }
````
在单独的页面使用
````kotlin
SwipeBack.getInstance().isRootSwipeBackEnable = false
SwipeBack.getInstance().isSwipeBackForceEdge = false
````
但是这个只在MainActivity里面有用，在别的页面里面没有用😂我是在MainActivity通过startActivity跳转的

**Comment by SaltedFish-Extreme** [comment]
我刚才又试了试，发现只有第一个设置
````kotlin
SwipeBack.getInstance().isRootSwipeBackEnable = false
SwipeBack.getInstance().isSwipeBackForceEdge = false
````
的页面有用，我本来闪屏页没继承基类所以没发现，这次换成在application里全局配置后，发现在闪屏页设置了这个之后，在MainActivity以及后面的页面再设置这个就没有用了😂

**Comment by SaltedFish-Extreme** [comment]
不对啊，我在刚跳转MainActivity的时候立马滑动边缘，也能退出关闭程序，这个配置是不是没有用啊，在单独的activity取消全局侧滑不是这么写吗？

**Comment by goweii** [comment]
看下readme，单activity配置使用实现接口的方式SwipeBackAbility.Xxx接口

**Comment by SaltedFish-Extreme** [comment]
> SwipeBackAbility

老哥，我是想全局应用之后，在单独的activity里面取消使用，还有这个默认就把第一个activity当作底部，但是第一个是闪屏页的话，跳转到MainActivity之后已经结束掉了，MainActivity应该作为底部，不应该能滑动才对🤔

**Comment by SaltedFish-Extreme** [comment]
话说这些接口都没有注释，我都看不明白都什么作用😂还有这个实现接口和重写方法的方式，对kotlin有点不大友好，能直接整个全局和单例变量出来控制侧滑吗🤔或者在Application里面初始化的时候可以指定哪一个Activity作为底部这样，然后在不需要侧滑的activity里面设置个属性不让这个页面侧滑🤔

**Comment by goweii** [comment]
最底部activity是根据最新的活动栈计算的，splase关闭之后会以现在的main当做底部的，不需要单独配置。

**Comment by SaltedFish-Extreme** [comment]
> 最底部activity是根据最新的活动栈计算的，splase关闭之后会以现在的main当做底部的，不需要单独配置。

这个？

https://user-images.githubusercontent.com/54784104/153184682-be611fbd-63e6-4fd7-a078-f1046ddc5028.mp4

**Comment by SaltedFish-Extreme** [comment]
因为我加了侧滑栏所以MainActivity都创建完成之后我就没录下去了，会有冲突，MainActivity的侧滑会被抽屉视图覆盖掉，但是不加抽屉视图的话，都加载完成之后也会出现MainActivity可以侧滑这种情况，我不知道这是什么问题，但是感觉可能是这个库的bug，老哥有时间试试看看吧🤔

**Comment by goweii** [comment]
可以的话，fork下库，新建个application module加下你这个现象的代码

**Comment by SaltedFish-Extreme** [comment]
> 可以的话，fork下库，新建个application module加下你这个现象的代码

我没有vpn，拉不下来代码，你觉得行的话，我可以整个demo发github仓库里😂

**Comment by SaltedFish-Extreme** [comment]
Application
````kotlin
        //全局配置侧滑返回activity
        SwipeBack.getInstance().run {
            //初始化侧滑返回
            init(this@MyApplication)
            //栈底不可滑动返回
            isRootSwipeBackEnable = false
            //强制边缘侧滑返回(横向列表适配器)
            isSwipeBackForceEdge = true
            //右滑方向
            swipeBackDirection = SwipeBackDirection.RIGHT
            //底部activity联动视差效果
            swipeBackTransformer = ParallaxSwipeBackTransformer()
        }
````
SplashActivity
````kotlin
val intent = Intent(this, MainActivity::class.java)
        startActivity(intent)
        finish()
````
其实代码就这几行，demo都不需要，MainActivity啥都没写

**Comment by SaltedFish-Extreme** [comment]
我把侧滑栏删了之后重新试了一遍，发现这种情况是刚跳转到MainActivity，但是MainActivity还没完全创建完的过程中出现的，在完全创建完之后就没问题了，是不是你侧滑的生命周期的问题？

https://user-images.githubusercontent.com/54784104/153202870-51d3123d-ee5a-4c94-ba3b-d81f082a98e3.mp4

**Comment by goweii** [comment]
了解了，周末处理下

**Comment by SaltedFish-Extreme** [comment]
> 了解了，周末处理下

辛苦老哥了😊

**Comment by goweii** [comment]
更新2.0.4版本

**Comment by SaltedFish-Extreme** [comment]
> 更新2.0.4版本

好的，麻烦老哥了，没问题了👌

话说我想要在某个页面取消侧滑或者是只能边缘侧滑应该怎么样单独配置😂

**Comment by SaltedFish-Extreme** [comment]
啊，我又看了看你的玩安卓app的web页面可以只边缘侧滑返回，继承了`SwipeBackAbility.OnlyEdge`接口，重写`swipeBackOnlyEdge()`方法返回true就好了，我之前都没注意到😂
话说继承`SwipeBackAbility.ForceEdge`重写`swipeBackForceEdge()`方法返回false不能取消侧滑，是没有单独页面取消侧滑的方法实现吗？

**Comment by goweii** [comment]
SwipeBackDirection.NONE

**Comment by SaltedFish-Extreme** [comment]
> SwipeBackDirection.NONE

老哥，这个好像是把全局侧滑方向改成空啊，这样就都不能侧滑了，有没有办法只让单独某一个页面不允许侧滑？继承接口重写方法啥的

**Comment by SaltedFish-Extreme** [comment]
不行的话也没事，能只允许边缘侧滑返回也可以了😂

**Comment by goweii** [comment]
实现SwipeBackAbility.Direction接口

**Comment by SaltedFish-Extreme** [comment]
> SwipeBackAbility.Direction

这样啊，我还以为是在代码里配置这个属性为NONE😂没问题了，麻烦老哥了😊
