### ISSUE TITLE
老哥，我又发现了一个不知道是不是bug的地方，我切换主题之后偶尔会闪屏底部的activity，而且这个时候切换的很卡，我试了很多次，如果不用这个侧滑返回的话是没问题的😂

### ISSUE THREAD

**Issue by SaltedFish-Extreme** [goweii/SwipeBack#13]
https://user-images.githubusercontent.com/54784104/153605713-1ecb3fde-e00c-4795-9245-a381e6f398f1.mp4

**Comment by goweii** [comment]
复现不到，建议fork提供复现module

**Comment by SaltedFish-Extreme** [comment]
> 复现不到，建议fork提供复现module

主要我这也不是必定出现，偶尔切换模式会出现，但是一关闭当前页面或者打开新页面再回来切换就没事了，不知道怎么搞的😂就这样吧🤔
