### ISSUE TITLE
唉，刚说完上一个问题，又发现了个问题，滑动页面时如果按下返回键会出现这种显示BUG，老哥看看是不是要改改显示效果😂

### ISSUE THREAD

**Issue by SaltedFish-Extreme** [goweii/SwipeBack#14]
好像是滑动未超过半屏按返回键会这样，如果超过半屏就会全显示出来🤔

![微信图片_20220212114819](https://user-images.githubusercontent.com/54784104/153695561-39e38da3-a38b-4456-b330-6b0ee91b455a.jpg)

https://user-images.githubusercontent.com/54784104/153695565-274463f4-d3e0-4abd-b087-a987082b298a.mp4

**Comment by goweii** [comment]
更新2.0.5

**Comment by SaltedFish-Extreme** [comment]
> 更新2.0.5

好的，麻烦老哥了😆
