### ISSUE TITLE
老哥，我好像知道为什么你这个切换夜间模式偶尔会闪屏了，而且切换之后底下的activity并没有切换主题，只是当前页面换了，因为我在侧滑返回主页时候在onActivityResult回调里执行recreate重建activity会黑屏闪屏，按返回键不会，我觉得你生命周期可能还有问题😂

### ISSUE THREAD

**Issue by SaltedFish-Extreme** [goweii/SwipeBack#15]
https://user-images.githubusercontent.com/54784104/155096946-989225dd-311c-4b38-8fa0-74cca908e36c.mp4

**Comment by SaltedFish-Extreme** [comment]
emmmm 我切换了主题之后好像又没这么明显了，感觉是个频发性的bug😅而且切换主题之后出现闪屏底部的activity时稍微侧滑一点再切换又不会出现了，我都不知道是什么问题了😅

**Comment by goweii** [comment]
onActivityResult中重建。在侧滑结束才会触发finish，然后才会触发onActivityResult回调，所以滑动结束会闪屏。

要想不闪屏只能考虑不要使用重建的方式实现主题，可以看下其他3方的主题框架。

**Comment by SaltedFish-Extreme** [comment]
> onActivityResult中重建。在侧滑结束才会触发finish，然后才会触发onActivityResult回调，所以滑动结束会闪屏。
> 
> 要想不闪屏只能考虑不要使用重建的方式实现主题，可以看下其他3方的主题框架。

唉，我现在把需要重建操作的页面不允许侧滑了😂
