### ISSUE TITLE
快速返回时出现黑边

### ISSUE THREAD

**Issue by JKXY** [goweii/SwipeBack#16]
https://user-images.githubusercontent.com/8470897/227073342-8fdd1c45-1797-495b-95e5-7ec9b59ebad2.mp4

Demo能复现出来，这个的视频里的黑边在右边，我在其他地方使用，发现也会出现在右边

**Comment by JKXY** [comment]
。。。看了下代码，好像是无解的

**Comment by goweii** [comment]
这个是因为activity主题是非透明的，滑动返回时会强制修改为透明的(需要看都前一个页面)。你可以把你的activity设置成透明的，应该可以避免这个情况。

**Comment by JKXY** [comment]
嗯嗯，我昨天看了下代码，知道了原因，不过我仔细分析了下，发现黑边有两种情况：
1.因为反射原因导致的左黑边，也就是你说的原因；
2.出现在右边的黑边，这种是跳转的转场动画未完成就快速滑动返回，这样就导致上层的页面已关闭下层页面动画未完成直接看到右边的黑边（与 跳转时进入动画和退出动画时长不一样看到黑边情况差不多）；

我目前想法思路：
1.针对第一种情况可以参考这个文章的思路 [https://juejin.cn/post/6844903560228896782](https://juejin.cn/post/6844903560228896782) ，他是透明完后才进行滑动，这也间接解决了你这个框架可能出现透明失败滑动返回黑底问题；
2.对第二种情况我的思路一个是在跳转时禁止滑动返回，还有一个是跳转时滑动返回要同步下层动画，但是这两个思路在代码层面我目前还不知道怎么实现，怎么去判断正在跳转等等

**Comment by goweii** [comment]
1、透明主题建议放到theme里面去设置，因为透明主题会带来一些其他问题，需要应用自己去适配。所以当时设计时只在非透明主题下才会在滑动开始时通过反射修改成透明，并且在滑动结束时恢复成非透明。
2、尽量不要因为一个滑动返回影响关闭页面的响应时间。闪黑属于可接受的视觉体验，但是动画时不能立刻响应关闭就属于影响操作体验了。

针对第二点，SwipeBackLayout有滑动事件的回调，可以自己监听实现下。
