### ISSUE TITLE
大佬，在有SmartRefreshLayout布局的地方，左滑失效了

### ISSUE THREAD

**Issue by diandian8801** [goweii/SwipeBack#20]
大佬，有一个自定义控件继承自SmartRefreshLayout。自定义控件中嵌套了一个recyclerview.

在activity中左滑失效了，好像被这个SmartRefreshLayout消耗掉了。 

找了半天，没有找到处理办法呢，需要哪些设置呢？

**Comment by goweii** [comment]
复写自定义控件的 canScrollHorizontally 方法返回 false 禁用掉水平滚动 。

**Comment by diandian8801** [comment]
多谢，大佬，无法滑动原来是AutoHidePanelRecyclerView控件里消耗掉了。

在原来自定义控件PageRefreshLayout 基础上，复写了自定义控件。添加了canScrollHorizontally 

`open class PageRefreshNoHLayout: PageRefreshLayout {
    constructor(context: Context) : this(context, null)
    constructor(context: Context, attrs: AttributeSet?) : super(context, attrs)

    override fun canScrollHorizontally(direction: Int): Boolean {
        return false
    }
}`
=================================
原PageRefreshLayout 控件: 
open class PageRefreshLayout : SmartRefreshLayout, OnRefreshLoadMoreListener {
}
=================================

复写的控件名称是：PageRefreshNoHLayout
它嵌套着AutoHidePanelRecyclerView控件。

=================================

AutoHidePanelRecyclerView代码如下：

`public class AutoHidePanelRecyclerView extends RecyclerView {
    PanelSwitchHelper panelSwitchHelper;


    public void setPanelSwitchHelper(PanelSwitchHelper panelSwitchHelper) {
        this.panelSwitchHelper = panelSwitchHelper;
    }

    public AutoHidePanelRecyclerView(Context context) {
        this(context, null);
    }

    public AutoHidePanelRecyclerView(Context context, @Nullable AttributeSet attrs) {
        this(context, attrs, 0);
    }


    public AutoHidePanelRecyclerView(Context context, @Nullable AttributeSet attrs, int defStyle) {
        super(context, attrs, defStyle);
        setLayoutManager(new LinearLayoutManager(context));
    }

    @Override
    public boolean onTouchEvent(MotionEvent e) {
        super.onTouchEvent(e);
        if (e != null && e.getAction() != MotionEvent.ACTION_CANCEL) {
            if (panelSwitchHelper != null) {
                panelSwitchHelper.hookSystemBackByPanelSwitcher();
            }
        }

        return true;
    }

    @Override
    public boolean dispatchTouchEvent(MotionEvent ev) {
        //通知父层ViewGroup不要拦截点击事件
        getParent().requestDisallowInterceptTouchEvent(true);
        return super.dispatchTouchEvent(ev);
    }
}`

===========
