### ISSUE TITLE
偶尔会卡倒，就是页面显示不全，但是页面没有卡死，可以滑动

### ISSUE THREAD

**Issue by csh159** [goweii/SwipeBack#3]
概率很小，基本是应用很久没用再开就会出现这种情况，而且概率不大这是为啥？

**Comment by csh159** [comment]
![Screenshot_20190618-105005](https://user-images.githubusercontent.com/4157414/59649948-f7dc5c00-91b6-11e9-8f91-d2375aeb1208.png)

**Comment by goweii** [comment]
是不是滑动返回刚开始那样显示不全？这个我再看下，这两天可能没时间更新了。

**Comment by csh159** [comment]
类似上面图片的样子

**Comment by goweii** [comment]
知道为啥了，有时间我再更新下

**Comment by csh159** [comment]
好的，谢谢！

**Comment by csh159** [comment]
兄弟，有时间改下上面的bug么？

**Comment by goweii** [comment]
这周末有时间我改下，周内太忙了，见谅

**Comment by csh159** [comment]
好的呢，谢谢啦

**Comment by goweii** [comment]
你试下1.0.3版，如果还有这个问题，麻烦记下复现方法，我好排查。

**Comment by csh159** [comment]
嗯嗯，谢谢
