### ISSUE TITLE
你好  如果项目使用了AndroidX   是不是不能引用这个

### ISSUE THREAD

**Issue by Mr-jinPH** [goweii/SwipeBack#4]
你好  如果项目使用了AndroidX   是不是不能引用这个

**Comment by goweii** [comment]
依赖了supportv7。androidx引用可能会有问题，也不一定，因为google有做自动迁移的，但还是不建议引用，可以自己fork下替换下依赖。

**Comment by Mr-jinPH** [comment]
> 依赖了supportv7.androidx引用可能会有问题，也不一定，因为谷歌有做自动迁移的，但还是不建议引用，可以自己叉下替换下依赖。

好的  感谢回复
