### ISSUE TITLE
请问一下如何使用？

### ISSUE THREAD

**Issue by SaltedFish-Extreme** [goweii/SwipeBack#9]
// 全局配置
SwipeBack.getInstance().setXxx();

这个全局配置的setXxx()是什么意思？找不到这个方法，现在只是在application中使用SwipeBack.getInstance().init(this)初始化了，还要怎么做才能全局配置呢？

**Comment by goweii** [comment]
setXxx()意思是set开头的方法。
单个activity修改配置实现swipebackability相关接口。

**Comment by SaltedFish-Extreme** [comment]
> setXxx()意思是set开头的方法。 单个activity修改配置实现swipebackability相关接口。

啊，怪不得，我用kotlin做的，代码提示里get和set放一起都是属性调用，怪不得没找到，加个注释就好了😂
![image](https://user-images.githubusercontent.com/54784104/146524841-162045c8-c1d8-4728-9b37-97c816800d47.png)
